# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lmao
org: uavgaming

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: go1.x

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  lmao:
    handler: bin/lmao
    memorySize: 128
    environment:
      DISCORD_TOKEN: ${env:DISCORD_TOKEN}
      DISCORD_GUILD_ID: ${env:DISCORD_GUILD_ID}
      DISCORD_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
