name: Build and Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    name: Build and deploy to AWS Lambda.
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'
      - name: Build binary
        run: make build
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}